const DATABASE_NAME = '@finances:database';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_TRANSACTIONS = `${DATABASE_NAME}:TRANSACTIONS`;

export {
    COLLECTION_USERS,
    COLLECTION_TRANSACTIONS
}