const DATABASE_NAME = '@finances:database';

const COLLECTION_USERS = `${DATABASE_NAME}:user`;
const COLLECTION_TRANSACTIONS = `${DATABASE_NAME}:TRANSACTIONS`;
const COLLECTION_AMOUNTS = `${DATABASE_NAME}:amounts`;

export {
    COLLECTION_USERS,
    COLLECTION_TRANSACTIONS,
    COLLECTION_AMOUNTS,
}